# Docker Containers for Hive API.
version: '3.7'

services:
   frontend:
      image: mia/empathy
      build:
         context: .
         target: frontend
         args:
            - NODE_ENV=development
      volumes:
         - .:/usr/src/app
         - /usr/src/app/node_modules
      ports:
         - '3000:3000' 
      command: npm start
